### ISSUE TITLE
Additional parameter to generate Delta report only with more than zero findings

### ISSUE THREAD

**Issue by acslf09** [HCL-TECH-SOFTWARE/ifa-client#1]
IFA delta analysis (parameter "-n") is used to find the diff. between latest and baseline assessment. Output file name can be specified using "-f" to generate delta assessment.

Is there a way (additional argument perhaps) to generate Delta assessment ONLY if there are new findings (i.e. more than zero new findings). Because currently it generates delta report no matter new findings exist or not and with zero findings it generates an empty report.

**Comment by kaddmann** [comment]
Added a -z switch to remove the returned assessment if the finding count is 0 for either a new or missing delta operation

**Comment by acslf09** [comment]
Can you please let me know the usage of this switch.
Is it something like:

java -jar "[ifa-client location]" -f "[DeltaFileName]" -n "[oldAssessmentFile]" "[newAssessmentFile]" -z

**Comment by kaddmann** [comment]
That is correct - adding the -z option will remove the returned assessment should it contain 0 findings as a result of the delta
