### ISSUE TITLE
IFA assessment folder path or assessment name cannot contain space

### ISSUE THREAD

**Issue by z10n0101** [HCL-TECH-SOFTWARE/ifa-client#2]
If there is a space character in folder path of assessment file name IFA will get confused and fail to start with exception: File does not exist or is inaccessible.

![IFA space in filename](https://user-images.githubusercontent.com/32577597/66302438-39754c00-e8f9-11e9-935c-b2770fbd2824.PNG)
![IFA space in path](https://user-images.githubusercontent.com/32577597/66302444-3b3f0f80-e8f9-11e9-8b88-3c79732f4083.PNG)

**Comment by kaddmann** [comment]
I am unable to reproduce this error. Have you tried the latest download of the client?

**Comment by kaddmann** [comment]
Closing. Let me know if you are still hitting this and we will take a peek.

**Comment by z10n0101** [comment]
Yap, it is working with latest version of the client. Thanks!
